version: '3'
services: 
  frontend:
    container_name: frontend
    build: 
      context: ../../
      dockerfile: ./ops/local/Dockerfile.dev
    ports:
      - "8080:8080"        
    volumes: 
      - ../../:/frontend:z
      - /frontend/node_modules
    environment:
     - PORT=8080
     - NODE_ENV=development
    restart: always